### ISSUE TITLE
suvaline meeleolumuusika

### ISSUE THREAD

**Issue by kk-boop** [kk-boop/n-team-se#1]
Commit b46fd8dd90bf382da673fa23cb17b3be9b3d20cb lisas taustamuusika
Kuidas oleks sellele vürtsi lisamisega?
Lisa õige veel mõni suvaline helin ja kasuta `Math.random()` ja `Math.floor()` funktsioone leidmaks nende seast iga kord mõni suvaline sinna.
Lisaks vihje, `document.getElementById().src` saad kasutada faili nime muutmiseks. Ideaalis paigutad muidugi `getElementId()` meetodi väljundi enne konstantsesse muutujasse.

**Comment by Mehisxd** [comment]
Tehtud!!!

**Comment by Mehisxd** [comment]
ups

**Comment by kk-boop** [comment]
Tere! Palun ärge lollitage Stuudiumi postkastis! Aitäh!
